version: "3.8"

services:
  web:
    build: .
    container_name: api8inf349
    ports:
      - "5000:5000"
    environment:
      REDIS_URL: redis://redis:6379
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: pass
      DB_PORT: 5432
      DB_NAME: api8inf349
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: api8inf349
    ports:
      - "5432:5432"
    # volumes:
    #   - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:5
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
